jupyter_notebook:
	. myenv/bin/activate && jupyter notebook

gradio_micropost:
	. myenv/bin/activate && python ./gradio/gradio_micropost.py

gradio_chatbot:
	. myenv/bin/activate && python ./gradio/gradio_chatbot.py

stop:
	. myenv/bin/deactivate

